# docker-compose_dev.yml
version: "2"
services:
  app:
    container_name: server_file_dev
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 main.py
    volumes:
      - /usr/local/volumes/fileserver_dev/uploads/:/app/uploads/:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "4444:4444"